### PR TITLE
Room page added successfully

### PR DESCRIPTION
**Pull request by dhruval-tech**
**The Front end code for following design is developed .**

webinar

**Design Look:**

Screenshot (692)

HTML ,CSS and Javascript is used to develop this page.
The chat section is still in progress, not completed yet.

### CODE REVIEW

**Comment by BaseMax** [comment]
Great,
Thank you. This is not yet what we expect.
But it is a good progress.
I am waiting for the next changes.

Merged.

**Comment by BaseMax** [comment]
Hi my friend, Good morning.
Any update? @dhruval-tech

**Comment by dhruval-tech** [comment]
Hey Max,

Good Morning,
Working on it.
Will update you soon.

Thank You.

**Comment by dhruval-tech** [comment]
Hi @BaseMax , Good morning.
Working on it,
Will update you on soon.

**Pull request merged**
